### ISSUE TITLE
[BUG] NFO:undetected_chromedriver.patcher:patching driver executable /Users/abcd/Library/Application Support/undetected_chromedriver/undetected_chromedriver INFO:root:[21/10/2023 01:11:24] Bing Image Creator (Dalle-3) Opened INFO:root:[21/10/2023 01:11:24] Cookie values added 

### ISSUE THREAD

**Issue by garciaraul85** [Agora-X/Dalle3#14]
**Describe the bug**
Getting this error:INFO:undetected_chromedriver.patcher:patching driver executable /Users/abcd/Library/Application Support/undetected_chromedriver/undetected_chromedriver
INFO:root:[21/10/2023 01:11:24] Bing Image Creator (Dalle-3) Opened
INFO:root:[21/10/2023 01:11:24] Cookie values added 
**To Reproduce**
When executing the example script from the readme I get the error:
Getting this error:INFO:undetected_chromedriver.patcher:patching driver executable /Users/abcd/Library/Application Support/undetected_chromedriver/undetected_chromedriver
INFO:root:[21/10/2023 01:11:24] Bing Image Creator (Dalle-3) Opened
INFO:root:[21/10/2023 01:11:24] Cookie values added

**Comment by kyegomez** [comment]
@garciaraul85 this isn't an error?

**Comment by toxoplasmotic** [comment]
The problem is that the script freezes at this point. It seems to just be hanging on the request. When I CTRL+C I see:
```
Traceback (most recent call last):
  File "C:\Users\toxop\Videos\generate_image.py", line 19, in <module>
    urls = dalle.get_urls()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\toxop\AppData\Local\Programs\Python\Python311\Lib\site-packages\dalle3\dalle.py", line 124, in get_urls
    for element in WebDriverWait(self.driver, 600).until(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\toxop\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    time.sleep(self._poll)
KeyboardInterrupt
Exception ignored in: <function Chrome.__del__ at 0x000002FB7B75DE40>
Traceback (most recent call last):
  File "C:\Users\toxop\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Users\toxop\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] The handle is invalid
```

**Comment by toxoplasmotic** [comment]
Or maybe Bing DALL-E is just hella slow!!

**Comment by j4yh3m** [comment]
I'm just trying it too, getting the same error. Generation in Bing image creator works but it's pretty slow and failing sometimes too. It could be due to network timeouts

**Comment by LouisDeconinck** [comment]
I'm having the same issue. Anyone managed to fix this?
