### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by infocyde** [Agora-X/Dalle3#5]
**Describe the bug**
Getting a  cannot import name 'Dalle3' from 'dalle3' (D:\_activeDev\dalle32\.venv\Lib\site-packages\dalle3\__init__.py)

**To Reproduce**
create a folder
install venv virtual environment
pip install python-dotenv, dalle3
Copy the initial code example.
Bug will display
maybe something to do with venv and the file structure?

**Comment by kyegomez** [comment]
@infocyde Did you pip install or git clone?

**Comment by infocyde** [comment]
I got an "swarms" module not found, so installing that...man that is a lot of dependencies...But hey, appreciate what you are trying to do here.  Keep up the good work.  I will let you know how it goes.

**Comment by infocyde** [comment]
Downloaded all sorts of dependencies and still getting errors.  Keep at it, but I'm moving on.

**Comment by kyegomez** [comment]
@infocyde Hey try this: "pip3 install --upgrade dalle3" I added that in 2 days ago.

And what errors are you getting?
