### ISSUE TITLE
[ERR0R]

### ISSUE THREAD

**Issue by Ion-ium** [Agora-X/Dalle3#7]
i have already pasted mybig cookie still error 

TypeError                                 Traceback (most recent call last)
[<ipython-input-14-42d0450a28e4>](https://localhost:8080/#) in <cell line: 13>()
     11 
     12 # Instantiate the Dalle class with your cookie value
---> 13 dalle = Dalle(cookie)
     14 
     15 # Open the website with your query

2 frames
[/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/options.py](https://localhost:8080/#) in binary_location(self, value)
     50         """
     51         if not isinstance(value, str):
---> 52             raise TypeError(self.BINARY_LOCATION_ERROR)
     53         self._binary_location = value
     54 

TypeError: Binary Location Must be a String

**Comment by kyegomez** [comment]
@Ion-ium Hey did you paste it in a string or the env file?

**Comment by kyegomez** [comment]
@stawiski how can we automate this check?

**Comment by stawiski** [comment]
@kyegomez build everything in Docker with all dependencies (including Chromium)

**Comment by kyegomez** [comment]
@stawiski can you help make the dockerfile for this?
