### ISSUE TITLE
Specify chrome driver version

### ISSUE THREAD

**Issue by iamshaynez** [Agora-X/Dalle3#9]
**Is your feature request related to a problem? Please describe.**
Github action environment doesnot support latest chrome driver version 118.

```
Error message:

This version of ChromeDriver only supports Chrome version 118\nCurrent browser version is 117.0.5938.0
```

**Describe the solution you'd like**
Maybe add a parameter to Dalle object or provide someway(environment variables) to manually assign version of chrome drive. Which eventually goes to undetected_chromedriver.Chrome.

```
   import undetected_chromedriver as uc
   driver = uc.Chrome( version_main = 95 )
```

**Comment by kyegomez** [comment]
@iamshaynez Hey this is a great idea, can you help with it?
